AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WalkFind Contest Serverless Infrastructure

Parameters:
  DbSecretArn:
    Type: String
    Description: ARN of the database secret (provided via SAM deploy parameters)
  CognitoIssuerUri:
    Type: String
    Description: Issuer URI of the Cognito User Pool (e.g. https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_xxxxxxxx)
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool used by API Gateway authorizer
  CognitoUserPoolId:
    Type: String
    Description: The ID of the Cognito User Pool (e.g. ap-northeast-1_xxxxx)

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Architectures:
      - arm64

  Api:

    BinaryMediaTypes:
      - multipart/form-data
      - image~1*

Resources:
  # =======================================================
  # SQS Queue (SAMにより自動作成)
  # =======================================================
  EmbeddingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: WalkFindEmbeddingQueue
      VisibilityTimeout: 310
      MessageRetentionPeriod: 1209600

  # =======================================================
  # Cognito User Pool
  # =======================================================
  WalkFindUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: WalkFindContestUserPool
      AutoVerifiedAttributes: [ email ]
      UsernameConfiguration:
        CaseSensitive: false

  WalkFindUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: WalkFindWebClient
      UserPoolId: !Ref WalkFindUserPool
      SupportedIdentityProviders: [ COGNITO ]

  # =======================================================
  # API Gateway
  # =======================================================
  WalkFindApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
      Auth:
        Authorizers:
          CognitoAuth:
            UserPoolArn: !Ref CognitoUserPoolArn

  # =======================================================
  # Lambda Function (Spring Boot)
  # =======================================================
  UserApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindUserApi
      Runtime: java17
      CodeUri: .
      AutoPublishAlias: live
      Handler: nagasawakenji.walkfind.handler.StreamLambdaHandler::handleRequest
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DbSecretArn
          COGNITO_ISSUER_URI: !Ref CognitoIssuerUri
          APP_DUMMY_VERSION: 2025-12-08-05
          S3_BUCKET_NAME: walkfind-photos
          EMBEDDING_QUEUE_URL: !Ref EmbeddingQueue
          WALKFIND_SQS_QUEUE_URL: !Ref EmbeddingQueue
          AWS_COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId

      Policies:
        - S3CrudPolicy:
            BucketName: walkfind-photos

        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/cognito/prod-*"
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt EmbeddingQueue.Arn
            - Effect: Allow
              Action:
                - cognito-idp:AdminDeleteUser
              Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"


      Events:
        AuthLogin:
          Type: Api
          Properties:
            Path: /api/v1/auth/cognito/login
            Method: ANY
            RestApiId: !Ref WalkFindApi
        AuthLogout:
          Type: Api
          Properties:
            Path: /api/v1/auth/logout
            Method: ANY
            RestApiId: !Ref WalkFindApi
        AuthMeDelete:
          Type: Api
          Properties:
            Path: /api/v1/auth/me
            Method: DELETE
            RestApiId: !Ref WalkFindApi
        AuthMeGet:
          Type: Api
          Properties:
            Path: /api/v1/auth/me
            Method: GET
            RestApiId: !Ref WalkFindApi
        ContestsRoot:
          Type: Api
          Properties:
            Path: /api/v1/contests
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ContestsProxy:
          Type: Api
          Properties:
            Path: /api/v1/contests/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        AdminRoot:
          Type: Api
          Properties:
            Path: /api/v1/admin
            Method: ANY
            RestApiId: !Ref WalkFindApi
        AdminProxy:
          Type: Api
          Properties:
            Path: /api/v1/admin/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ResultsRoot:
          Type: Api
          Properties:
            Path: /api/v1/results
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ResultsProxy:
          Type: Api
          Properties:
            Path: /api/v1/results/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        UsersRoot:
          Type: Api
          Properties:
            Path: /api/v1/users
            Method: ANY
            RestApiId: !Ref WalkFindApi
        UsersProxy:
          Type: Api
          Properties:
            Path: /api/v1/users/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        BioRoot:
          Type: Api
          Properties:
            Path: /api/v1/me/profile/bio
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ImageRoot:
          Type: Api
          Properties:
            Path: /api/v1/me/profile/image
            Method: ANY
            RestApiId: !Ref WalkFindApi
        VotesRoot:
          Type: Api
          Properties:
            Path: /api/v1/votes
            Method: ANY
            RestApiId: !Ref WalkFindApi
        VotesProxy:
          Type: Api
          Properties:
            Path: /api/v1/votes/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        PhotosRoot:
          Type: Api
          Properties:
            Path: /api/v1/photos
            Method: ANY
            RestApiId: !Ref WalkFindApi
        PhotosProxy:
          Type: Api
          Properties:
            Path: /api/v1/photos/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        MeApi:
          Type: Api
          Properties:
            Path: /api/v1/users/me
            Method: ANY
            RestApiId: !Ref WalkFindApi
        UploadRoot:
          Type: Api
          Properties:
            Path: /api/v1/upload
            Method: ANY
            RestApiId: !Ref WalkFindApi
        UploadProxy:
          Type: Api
          Properties:
            Path: /api/v1/upload/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ModelPhotosRoot:
          Type: Api
          Properties:
            Path: /api/v1/model-photos
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ModelPhotosProxy:
          Type: Api
          Properties:
            Path: /api/v1/model-photos/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ContestIconsRoot:
          Type: Api
          Properties:
            Path: /api/v1/contest-icons
            Method: ANY
            RestApiId: !Ref WalkFindApi
        ContestIconsProxy:
          Type: Api
          Properties:
            Path: /api/v1/contest-icons/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi

      SnapStart:
        ApplyOn: PublishedVersions

  ResultCalculationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindResultCalculation
      CodeUri: .
      Handler: nagasawakenji.walkfind.handler.ResultCalculationHandler::handleRequest
      Runtime: java17
      Timeout: 120
      MemorySize: 2048
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DbSecretArn
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/cognito/prod-*"
      Events:
        ResultCalculationSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
            Enabled: true

  ContestStatusBatchHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindContestStatusBatch
      CodeUri: .
      Handler: nagasawakenji.walkfind.handler.ContestStatusBatchHandler::handleRequest
      Runtime: java17
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DbSecretArn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/cognito/prod-*"
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt EmbeddingQueue.Arn
      Events:
        ContestStatusSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
            Enabled: true

  # =======================================================
  # ML Worker Function (Docker Container)
  # =======================================================
  EmbeddingWorkerFunctionV2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindEmbeddingWorkerV2
      PackageType: Image # Docker Imageを使用
      Timeout: 900
      MemorySize: 2048
      Runtime: python3.11

      Environment:
        Variables:
          STORAGE_PROVIDER: s3
          S3_BUCKET_NAME: walkfind-photos
          DB_SECRET_ID: !Ref DbSecretArn
          # Dockerコンテナ内のパス設定
          PYTHONPATH: /var/task/src:/var/task
          # openclipがどうしても指定ファイルにデータを保存しないので、homeをtmp指定します
          # もっと良い解決策があれば、後で変更します
          HOME: /tmp

          XDG_CACHE_HOME: /tmp/.cache
          TORCH_HOME: /tmp/.torch
          HF_HOME: /tmp/.hf

      Policies:
        - S3ReadPolicy:
            BucketName: walkfind-photos
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ChangeMessageVisibility
              Resource: !GetAtt EmbeddingQueue.Arn
      Events:
        EmbeddingQueueEvent:
          Type: SQS
          Properties:
            # 自動作成されたQueueのARNを参照
            Queue: !GetAtt EmbeddingQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures

    # Dockerビルドの設定
    Metadata:
      DockerTag: python3.11-v1
      DockerContext: ../walkfind-ml-worker
      Dockerfile: Dockerfile

Outputs:
  WalkFindApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WalkFindApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref WalkFindUserPool

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref WalkFindUserPoolClient