AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WalkFind Contest Serverless Infrastructure

Parameters:
  DbSecretArn:
    Type: String
    Description: ARN of the database secret (provided via SAM deploy parameters)
  CognitoIssuerUri:
    Type: String
    Description: Issuer URI of the Cognito User Pool (e.g. https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_xxxxxxxx)
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool used by API Gateway authorizer

Globals:
  Function:
    Runtime: java17
    Timeout: 30
    MemorySize: 1024
    Architectures:
      - x86_64

Resources:
  # =======================================================
  # 1. Cognito User Pool
  # =======================================================
  WalkFindUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: WalkFindContestUserPool
      AutoVerifiedAttributes: [ email ]
      UsernameConfiguration:
        CaseSensitive: false

  WalkFindUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: WalkFindWebClient
      UserPoolId: !Ref WalkFindUserPool
      SupportedIdentityProviders: [ COGNITO ]

  # =======================================================
  # 2. API Gateway
  # =======================================================
  WalkFindApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        Authorizers:
          CognitoAuth:
            UserPoolArn: !Ref CognitoUserPoolArn
      # ★重要: SAM側のグローバルCORS設定は削除済み（Spring Securityに任せるため）

  # =======================================================
  # 3. Lambda Function (Spring Boot)
  # =======================================================
  UserApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindUserApi
      CodeUri: .
      Handler: nagasawakenji.walkfind.handler.StreamLambdaHandler::handleRequest
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DbSecretArn
          COGNITO_ISSUER_URI: !Ref CognitoIssuerUri
          APP_DUMMY_VERSION: 2025-12-08-03 # バージョン上げ

      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/cognito/prod-*"

      Events:
        # -----------------------------------------
        # 認証不要：auth（Cognito ログイン）
        # ★ここを修正！ POST -> ANY
        # -----------------------------------------
        AuthLogin:
          Type: Api
          Properties:
            Path: /api/v1/auth/cognito/login
            Method: ANY  # <--- これが修正ポイント！OPTIONSを通すため必須
            RestApiId: !Ref WalkFindApi
            # Authなし（public）

        # -----------------------------------------
        # 認証不要：contests
        # -----------------------------------------
        ContestsRoot:
          Type: Api
          Properties:
            Path: /api/v1/contests
            Method: ANY
            RestApiId: !Ref WalkFindApi

        ContestsProxy:
          Type: Api
          Properties:
            Path: /api/v1/contests/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi

        # -----------------------------------------
        # 認証不要：results
        # -----------------------------------------
        ResultsRoot:
          Type: Api
          Properties:
            Path: /api/v1/results
            Method: ANY
            RestApiId: !Ref WalkFindApi

        ResultsProxy:
          Type: Api
          Properties:
            Path: /api/v1/results/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi

        # -----------------------------------------
        # 認証不要：users（/me 以外）
        # -----------------------------------------
        UsersRoot:
          Type: Api
          Properties:
            Path: /api/v1/users
            Method: ANY
            RestApiId: !Ref WalkFindApi

        UsersProxy:
          Type: Api
          Properties:
            Path: /api/v1/users/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi

        # -----------------------------------------
        # 認証必要：votes
        # -----------------------------------------
        VotesRoot:
          Type: Api
          Properties:
            Path: /api/v1/votes
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        VotesProxy:
          Type: Api
          Properties:
            Path: /api/v1/votes/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        # -----------------------------------------
        # 認証必要：photos
        # -----------------------------------------
        PhotosRoot:
          Type: Api
          Properties:
            Path: /api/v1/photos
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        PhotosProxy:
          Type: Api
          Properties:
            Path: /api/v1/photos/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        # -----------------------------------------
        # 認証必要：/users/me
        # -----------------------------------------
        MeApi:
          Type: Api
          Properties:
            Path: /api/v1/users/me
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        # -----------------------------------------
        # 認証必要：upload（presigned URL）
        # -----------------------------------------
        UploadRoot:
          Type: Api
          Properties:
            Path: /api/v1/upload
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        UploadProxy:
          Type: Api
          Properties:
            Path: /api/v1/upload/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth


        # -----------------------------------------
        # 認証必要：model-photos
        # -----------------------------------------
        ModelPhotosRoot:
          Type: Api
          Properties:
            Path: /api/v1/model-photos
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

        ModelPhotosProxy:
          Type: Api
          Properties:
            Path: /api/v1/model-photos/{proxy+}
            Method: ANY
            RestApiId: !Ref WalkFindApi
            Auth:
              Authorizer: CognitoAuth

  ResultCalculationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindResultCalculation
      CodeUri: .
      Handler: nagasawakenji.walkfind.handler.ResultCalculationHandler::handleRequest
      Runtime: java17
      Timeout: 120
      MemorySize: 2048
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DbSecretArn
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
      Events:
        ResultCalculationSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
            Enabled: true

  ContestStatusBatchHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalkFindContestStatusBatch
      CodeUri: .
      Handler: nagasawakenji.walkfind.handler.ContestStatusBatchHandler::handleRequest
      Runtime: java17
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DbSecretArn
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/walkfind/database-*"
      Events:
        ContestStatusSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
            Enabled: true

Outputs:
  WalkFindApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WalkFindApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref WalkFindUserPool

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref WalkFindUserPoolClient